# Generated by Django 5.2.1 on 2025-05-31 13:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, default=None, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateField(default=datetime.datetime.today)),
                ('comment', models.CharField(blank=True, default=None, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, default=None, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('confirmation_code', models.CharField(max_length=10, unique=True)),
                ('confirmation_date', models.DateField(default=datetime.datetime.today)),
                ('comment', models.CharField(blank=True, default=None, max_length=450, null=True)),
            ],
            options={
                'ordering': ['-confirmation_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('invoice_date', models.DateField(default=datetime.datetime.today)),
                ('comment', models.CharField(blank=True, default=None, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=450, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=450)),
                ('order_date', models.DateField()),
                ('comment', models.CharField(blank=True, default=None, max_length=450, null=True)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricelist_date', models.DateField(default=datetime.date.today)),
                ('state', models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Valid', max_length=50)),
                ('starts_from', models.DateField(default=datetime.date.today)),
                ('comment', models.CharField(blank=True, default=None, max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(blank=True, default=None, max_length=450, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_products', to='ordertrack_app.client')),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordertrack_app.confirmation')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cancellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordertrack_app.cancellation')),
                ('cancellation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled', to='ordertrack_app.confirmationitem')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmationitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoiced', to='ordertrack_app.confirmationitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordertrack_app.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='confirmation',
            name='order',
            field=models.ManyToManyField(related_name='confirmations', to='ordertrack_app.order'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('second_id', models.CharField(max_length=200, null=True, unique=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Valid', max_length=50)),
                ('comment', models.CharField(blank=True, default=None, max_length=450, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ordertrack_app.brand')),
            ],
        ),
        migrations.AddField(
            model_name='confirmationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed', to='ordertrack_app.product'),
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ordertrack_app.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ordertrack_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, default=None, max_length=450, null=True)),
                ('brand', models.ManyToManyField(related_name='suppliers', to='ordertrack_app.brand')),
            ],
        ),
        migrations.AddField(
            model_name='pricelist',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelists', to='ordertrack_app.supplier'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ordertrack_app.supplier'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='ordertrack_app.supplier'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='ordertrack_app.supplier'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='ordertrack_app.supplier'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='ordertrack_app.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordertrack_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='ordertrack_app.product')),
            ],
            options={
                'unique_together': {('order', 'client', 'product')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='confirmationitem',
            unique_together={('confirmation', 'client', 'product')},
        ),
        migrations.CreateModel(
            name='ConfirmationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_data', to='ordertrack_app.confirmation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_data', to='ordertrack_app.product')),
            ],
            options={
                'unique_together': {('confirmation', 'product', 'delivery_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('name', 'invoice_date')},
        ),
    ]
