# Generated by Django 5.2 on 2025-05-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordertrack_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmation',
            options={'ordering': ['-confirmation_date']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
    ]
