# Generated by Django 5.2 on 2025-05-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordertrack_app', '0002_alter_confirmation_options_alter_order_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='confirmationdelivery',
            unique_together={('confirmation', 'product', 'delivery_date')},
        ),
    ]
