# Generated by Django 5.2 on 2025-05-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertrack_app', '0003_alter_confirmationdelivery_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationdelivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
